---
- hosts: all
  name: setup node and user
  user: ghost
  become: yes
  vars_files:
    - ../config.yml
  tasks:
    - name: add node apt key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      tags:
        - apt
    - name: setup node apt repo
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
      tags:
        - apt
    - name: install node
      apt:
        name: nodejs
      tags:
        - apt
